% About

This repository is a part of results of my PhD project. I am working on improvement of potato late blight management in Ireland.   
Here I present the results of the field trial, set up to evaluate the opportunities for the IPM of potato late blight under Irish conditions.  
We looked into potential for using the environmental disease risk prediction, varietal resistance and infrmation on the pathogen population for the reduction of the pesticide usage.

 The funding for this project comes from [DAFM (Department of Agriculture, Food and Marine)](https://www.agriculture.gov.ie).  
   
The repository is built on the example research compendium provided by Emerson Del Ponte [here](https://github.com/emdelponte/research-compendium-website).
  
### Previous work
**The open-access publication of the manuscript where we have presented the preceding work on the evaluation of the Irish Rules, potato late blight risk model used in Ireland, can be found** [here](https://www.mdpi.com/2073-4395/9/9/515).  
The accompanying compendium with open access to the code is [here.](https://mladencucak.github.io/AnalysisPLBIreland/)

## The location

```{r map, echo=FALSE}
library("leaflet")
greenLeafIcon <- makeIcon(
  iconUrl = "http://leafletjs.com/examples/custom-icons/leaf-green.png",
  iconWidth = 38, iconHeight = 95,
  iconAnchorX = 22, iconAnchorY = 94,
  shadowUrl = "http://leafletjs.com/examples/custom-icons/leaf-shadow.png",
  shadowWidth = 50, shadowHeight = 64,
  shadowAnchorX = 4, shadowAnchorY = 62
)

leaflet() %>%
  addTiles(group = "OSM (default)") %>%
    setView(-8, 53.5, 6) %>%
  addMarkers(
    lng = -6.9121167,
    lat = 52.8560667,
    label = "Oak Park",
    icon = greenLeafIcon
  )

```

## Notes 

Some code chunks are folded and they can be accessed by clicking on the arrow (The code).  
Try not to have other R sessions running because it could produce problems installing libraries.  
If there are any problems reproducing the analysis, please raise an issue on GitHub.  

## Project team

Maynooth University:
- [Rowan Fealy](https://www.maynoothuniversity.ie/people/rowan-fealy)

Teagasc:
- [Stephen Kildea](https://www.teagasc.ie/contact/staff-directory/k/steven-kildea/)

Met Eirean:
- [Keith Lambkin](https://www.researchgate.net/profile/Keith_Lambkin)

University of Southern Queensland:
- [Adam Sparks](https://adamhsparks.netlify.com/)


<!-- ## Citation -->

<!-- Please cite this research compendium as: -->


<!-- > Cucak, M., Sparks, A., Fealy, R., Lambkin, K., and Kildea, S. 2019. Evaluation of the Irish Rules, a potato late blight forecasting used in Ireland.  -->

## Licences

Data: [CC-0](https://creativecommons.org/publicdomain/zero/1.0/) attribution requested in reuse
Manuscript: [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)  
Code: [MIT](https://opensource.org/licenses/MIT) year: 2019, copyright holder: Mladen Cucak

## Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.html). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.html). By participating in this project you agree to abide by its terms.
